# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arista.bugexposure.v1.services import gen_pb2 as arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in arista/bugexposure.v1/services.gen_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BugExposureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/arista.bugexposure.v1.BugExposureService/GetOne',
                request_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureRequest.SerializeToString,
                response_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureResponse.FromString,
                _registered_method=True)
        self.GetAll = channel.unary_stream(
                '/arista.bugexposure.v1.BugExposureService/GetAll',
                request_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.SerializeToString,
                response_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/arista.bugexposure.v1.BugExposureService/Subscribe',
                request_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.SerializeToString,
                response_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamResponse.FromString,
                _registered_method=True)
        self.GetMeta = channel.unary_unary(
                '/arista.bugexposure.v1.BugExposureService/GetMeta',
                request_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.SerializeToString,
                response_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
                _registered_method=True)
        self.SubscribeMeta = channel.unary_stream(
                '/arista.bugexposure.v1.BugExposureService/SubscribeMeta',
                request_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.SerializeToString,
                response_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
                _registered_method=True)


class BugExposureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BugExposureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureRequest.FromString,
                    response_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.FromString,
                    response_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.FromString,
                    response_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamResponse.SerializeToString,
            ),
            'GetMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeta,
                    request_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.FromString,
                    response_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.MetaResponse.SerializeToString,
            ),
            'SubscribeMeta': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeMeta,
                    request_deserializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.FromString,
                    response_serializer=arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.MetaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arista.bugexposure.v1.BugExposureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arista.bugexposure.v1.BugExposureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BugExposureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arista.bugexposure.v1.BugExposureService/GetOne',
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureRequest.SerializeToString,
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arista.bugexposure.v1.BugExposureService/GetAll',
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.SerializeToString,
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arista.bugexposure.v1.BugExposureService/Subscribe',
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.SerializeToString,
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arista.bugexposure.v1.BugExposureService/GetMeta',
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.SerializeToString,
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arista.bugexposure.v1.BugExposureService/SubscribeMeta',
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.BugExposureStreamRequest.SerializeToString,
            arista_dot_bugexposure_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
