[mypy]
warn_unreachable = True
ignore_missing_imports = True

[mypy-arista.*,fmp.*]
ignore_missing_imports = True
ignore_errors = True

[mypy-cloudvision.api.arista.*,cloudvision.api.fmp.*]
ignore_missing_imports = True
ignore_errors = True
