# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arista/lifecycle.v1/lifecycle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from fmp import extensions_pb2 as fmp_dot_extensions__pb2
from fmp import wrappers_pb2 as fmp_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arista/lifecycle.v1/lifecycle.proto',
  package='arista.lifecycle.v1',
  syntax='proto3',
  serialized_options=b'\n\027com.arista.lifecycle.v1B\tLifecycleP\001Z.arista/resources/arista/lifecycle.v1;lifecycle',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#arista/lifecycle.v1/lifecycle.proto\x12\x13\x61rista.lifecycle.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14\x66mp/extensions.proto\x1a\x12\x66mp/wrappers.proto\"R\n\x19\x44\x65viceLifecycleSummaryKey\x12/\n\tdevice_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue:\x04\x80\x8e\x19\x01\"p\n\x0bSoftwareEOL\x12-\n\x07version\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0e\x65nd_of_support\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"^\n\rDateAndModels\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12#\n\x06models\x18\x02 \x01(\x0b\x32\x13.fmp.MapStringInt32\"\x96\x02\n\x18HardwareLifecycleSummary\x12\x37\n\x0b\x65nd_of_life\x18\x01 \x01(\x0b\x32\".arista.lifecycle.v1.DateAndModels\x12\x37\n\x0b\x65nd_of_sale\x18\x02 \x01(\x0b\x32\".arista.lifecycle.v1.DateAndModels\x12>\n\x12\x65nd_of_tac_support\x18\x03 \x01(\x0b\x32\".arista.lifecycle.v1.DateAndModels\x12H\n\x1c\x65nd_of_hardware_rma_requests\x18\x04 \x01(\x0b\x32\".arista.lifecycle.v1.DateAndModels\"\xe8\x01\n\x16\x44\x65viceLifecycleSummary\x12;\n\x03key\x18\x01 \x01(\x0b\x32..arista.lifecycle.v1.DeviceLifecycleSummaryKey\x12\x36\n\x0csoftware_eol\x18\x02 \x01(\x0b\x32 .arista.lifecycle.v1.SoftwareEOL\x12Q\n\x1ahardware_lifecycle_summary\x18\x03 \x01(\x0b\x32-.arista.lifecycle.v1.HardwareLifecycleSummary:\x06\xfa\x8d\x19\x02roBV\n\x17\x63om.arista.lifecycle.v1B\tLifecycleP\x01Z.arista/resources/arista/lifecycle.v1;lifecycleb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,fmp_dot_extensions__pb2.DESCRIPTOR,fmp_dot_wrappers__pb2.DESCRIPTOR,])




_DEVICELIFECYCLESUMMARYKEY = _descriptor.Descriptor(
  name='DeviceLifecycleSummaryKey',
  full_name='arista.lifecycle.v1.DeviceLifecycleSummaryKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='arista.lifecycle.v1.DeviceLifecycleSummaryKey.device_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\200\216\031\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=249,
)


_SOFTWAREEOL = _descriptor.Descriptor(
  name='SoftwareEOL',
  full_name='arista.lifecycle.v1.SoftwareEOL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='arista.lifecycle.v1.SoftwareEOL.version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_of_support', full_name='arista.lifecycle.v1.SoftwareEOL.end_of_support', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=363,
)


_DATEANDMODELS = _descriptor.Descriptor(
  name='DateAndModels',
  full_name='arista.lifecycle.v1.DateAndModels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='arista.lifecycle.v1.DateAndModels.date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='models', full_name='arista.lifecycle.v1.DateAndModels.models', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=459,
)


_HARDWARELIFECYCLESUMMARY = _descriptor.Descriptor(
  name='HardwareLifecycleSummary',
  full_name='arista.lifecycle.v1.HardwareLifecycleSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='end_of_life', full_name='arista.lifecycle.v1.HardwareLifecycleSummary.end_of_life', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_of_sale', full_name='arista.lifecycle.v1.HardwareLifecycleSummary.end_of_sale', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_of_tac_support', full_name='arista.lifecycle.v1.HardwareLifecycleSummary.end_of_tac_support', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_of_hardware_rma_requests', full_name='arista.lifecycle.v1.HardwareLifecycleSummary.end_of_hardware_rma_requests', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=740,
)


_DEVICELIFECYCLESUMMARY = _descriptor.Descriptor(
  name='DeviceLifecycleSummary',
  full_name='arista.lifecycle.v1.DeviceLifecycleSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arista.lifecycle.v1.DeviceLifecycleSummary.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='software_eol', full_name='arista.lifecycle.v1.DeviceLifecycleSummary.software_eol', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hardware_lifecycle_summary', full_name='arista.lifecycle.v1.DeviceLifecycleSummary.hardware_lifecycle_summary', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\372\215\031\002ro',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=743,
  serialized_end=975,
)

_DEVICELIFECYCLESUMMARYKEY.fields_by_name['device_id'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_SOFTWAREEOL.fields_by_name['version'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_SOFTWAREEOL.fields_by_name['end_of_support'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DATEANDMODELS.fields_by_name['date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DATEANDMODELS.fields_by_name['models'].message_type = fmp_dot_wrappers__pb2._MAPSTRINGINT32
_HARDWARELIFECYCLESUMMARY.fields_by_name['end_of_life'].message_type = _DATEANDMODELS
_HARDWARELIFECYCLESUMMARY.fields_by_name['end_of_sale'].message_type = _DATEANDMODELS
_HARDWARELIFECYCLESUMMARY.fields_by_name['end_of_tac_support'].message_type = _DATEANDMODELS
_HARDWARELIFECYCLESUMMARY.fields_by_name['end_of_hardware_rma_requests'].message_type = _DATEANDMODELS
_DEVICELIFECYCLESUMMARY.fields_by_name['key'].message_type = _DEVICELIFECYCLESUMMARYKEY
_DEVICELIFECYCLESUMMARY.fields_by_name['software_eol'].message_type = _SOFTWAREEOL
_DEVICELIFECYCLESUMMARY.fields_by_name['hardware_lifecycle_summary'].message_type = _HARDWARELIFECYCLESUMMARY
DESCRIPTOR.message_types_by_name['DeviceLifecycleSummaryKey'] = _DEVICELIFECYCLESUMMARYKEY
DESCRIPTOR.message_types_by_name['SoftwareEOL'] = _SOFTWAREEOL
DESCRIPTOR.message_types_by_name['DateAndModels'] = _DATEANDMODELS
DESCRIPTOR.message_types_by_name['HardwareLifecycleSummary'] = _HARDWARELIFECYCLESUMMARY
DESCRIPTOR.message_types_by_name['DeviceLifecycleSummary'] = _DEVICELIFECYCLESUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceLifecycleSummaryKey = _reflection.GeneratedProtocolMessageType('DeviceLifecycleSummaryKey', (_message.Message,), {
  'DESCRIPTOR' : _DEVICELIFECYCLESUMMARYKEY,
  '__module__' : 'arista.lifecycle.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:arista.lifecycle.v1.DeviceLifecycleSummaryKey)
  })
_sym_db.RegisterMessage(DeviceLifecycleSummaryKey)

SoftwareEOL = _reflection.GeneratedProtocolMessageType('SoftwareEOL', (_message.Message,), {
  'DESCRIPTOR' : _SOFTWAREEOL,
  '__module__' : 'arista.lifecycle.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:arista.lifecycle.v1.SoftwareEOL)
  })
_sym_db.RegisterMessage(SoftwareEOL)

DateAndModels = _reflection.GeneratedProtocolMessageType('DateAndModels', (_message.Message,), {
  'DESCRIPTOR' : _DATEANDMODELS,
  '__module__' : 'arista.lifecycle.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:arista.lifecycle.v1.DateAndModels)
  })
_sym_db.RegisterMessage(DateAndModels)

HardwareLifecycleSummary = _reflection.GeneratedProtocolMessageType('HardwareLifecycleSummary', (_message.Message,), {
  'DESCRIPTOR' : _HARDWARELIFECYCLESUMMARY,
  '__module__' : 'arista.lifecycle.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:arista.lifecycle.v1.HardwareLifecycleSummary)
  })
_sym_db.RegisterMessage(HardwareLifecycleSummary)

DeviceLifecycleSummary = _reflection.GeneratedProtocolMessageType('DeviceLifecycleSummary', (_message.Message,), {
  'DESCRIPTOR' : _DEVICELIFECYCLESUMMARY,
  '__module__' : 'arista.lifecycle.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:arista.lifecycle.v1.DeviceLifecycleSummary)
  })
_sym_db.RegisterMessage(DeviceLifecycleSummary)


DESCRIPTOR._options = None
_DEVICELIFECYCLESUMMARYKEY._options = None
_DEVICELIFECYCLESUMMARY._options = None
# @@protoc_insertion_point(module_scope)
