"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2024 Arista Networks, Inc.  All rights reserved.
Arista Networks, Inc. Confidential and Proprietary.
Subject to Arista Networks, Inc.'s EULA.
FOR INTERNAL USE ONLY. NOT FOR DISTRIBUTION.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SortDirection:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SortDirectionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SortDirection.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SORT_DIRECTION_UNSPECIFIED: _SortDirection.ValueType  # 0
    """SORT_DIRECTION_UNSPECIFIED means that no sort direction specified."""
    SORT_DIRECTION_ASCENDING: _SortDirection.ValueType  # 1
    """SORT_DIRECTION_ASCENDING sorts in ascending order."""
    SORT_DIRECTION_DESCENDING: _SortDirection.ValueType  # 2
    """SORT_DIRECTION_DESCENDING sorts in descending order."""

class SortDirection(_SortDirection, metaclass=_SortDirectionEnumTypeWrapper):
    """SortDirection is an enum of possible values for direction of sorting."""

SORT_DIRECTION_UNSPECIFIED: SortDirection.ValueType  # 0
"""SORT_DIRECTION_UNSPECIFIED means that no sort direction specified."""
SORT_DIRECTION_ASCENDING: SortDirection.ValueType  # 1
"""SORT_DIRECTION_ASCENDING sorts in ascending order."""
SORT_DIRECTION_DESCENDING: SortDirection.ValueType  # 2
"""SORT_DIRECTION_DESCENDING sorts in descending order."""
global___SortDirection = SortDirection
