type: ACTION
language: PYTHON_3
name: Sleep
description: Sleeps for a given duration during a Change Control
file: script.py
static-params: []
dynamic-params:
  - name: duration
    description: Duration in seconds to sleep for. Defaults to 30 seconds
    required: false
    hidden: false
    default: "30"
