# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloudvision.arista.identityprovider.v1.services import gen_pb2 as cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2


class OAuthConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetOne',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigResponse.FromString,
                )
        self.GetSome = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetSome',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSomeRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSomeResponse.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetAll',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/Subscribe',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamResponse.FromString,
                )
        self.GetMeta = channel.unary_unary(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetMeta',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
                )
        self.SubscribeMeta = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/SubscribeMeta',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
                )
        self.Set = channel.unary_unary(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/Set',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetResponse.FromString,
                )
        self.SetSome = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/SetSome',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetSomeRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetSomeResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/Delete',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteResponse.FromString,
                )
        self.DeleteSome = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/DeleteSome',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteSomeRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteSomeResponse.FromString,
                )
        self.DeleteAll = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/DeleteAll',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteAllRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteAllResponse.FromString,
                )
        self.GetAllBatched = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetAllBatched',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamResponse.FromString,
                )
        self.SubscribeBatched = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.OAuthConfigService/SubscribeBatched',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamResponse.FromString,
                )


class OAuthConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBatched(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeBatched(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OAuthConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigResponse.SerializeToString,
            ),
            'GetSome': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSome,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSomeRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSomeResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamResponse.SerializeToString,
            ),
            'GetMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeta,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.SerializeToString,
            ),
            'SubscribeMeta': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeMeta,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetResponse.SerializeToString,
            ),
            'SetSome': grpc.unary_stream_rpc_method_handler(
                    servicer.SetSome,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetSomeRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetSomeResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteResponse.SerializeToString,
            ),
            'DeleteSome': grpc.unary_stream_rpc_method_handler(
                    servicer.DeleteSome,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteSomeRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteSomeResponse.SerializeToString,
            ),
            'DeleteAll': grpc.unary_stream_rpc_method_handler(
                    servicer.DeleteAll,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteAllRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteAllResponse.SerializeToString,
            ),
            'GetAllBatched': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllBatched,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamResponse.SerializeToString,
            ),
            'SubscribeBatched': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeBatched,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudvision.arista.identityprovider.v1.OAuthConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OAuthConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetOne',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetSome',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSomeRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSomeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetAll',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/Subscribe',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetMeta',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/SubscribeMeta',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/Set',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/SetSome',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetSomeRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigSetSomeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/Delete',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/DeleteSome',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteSomeRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteSomeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/DeleteAll',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteAllRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigDeleteAllResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllBatched(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/GetAllBatched',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeBatched(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.OAuthConfigService/SubscribeBatched',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.OAuthConfigBatchedStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SAMLConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetOne',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigResponse.FromString,
                )
        self.GetSome = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetSome',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSomeRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSomeResponse.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetAll',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/Subscribe',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamResponse.FromString,
                )
        self.GetMeta = channel.unary_unary(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetMeta',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
                )
        self.SubscribeMeta = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/SubscribeMeta',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
                )
        self.Set = channel.unary_unary(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/Set',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetResponse.FromString,
                )
        self.SetSome = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/SetSome',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetSomeRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetSomeResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/Delete',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteResponse.FromString,
                )
        self.DeleteSome = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/DeleteSome',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteSomeRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteSomeResponse.FromString,
                )
        self.DeleteAll = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/DeleteAll',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteAllRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteAllResponse.FromString,
                )
        self.GetAllBatched = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetAllBatched',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamResponse.FromString,
                )
        self.SubscribeBatched = channel.unary_stream(
                '/cloudvision.arista.identityprovider.v1.SAMLConfigService/SubscribeBatched',
                request_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamRequest.SerializeToString,
                response_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamResponse.FromString,
                )


class SAMLConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBatched(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeBatched(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SAMLConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigResponse.SerializeToString,
            ),
            'GetSome': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSome,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSomeRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSomeResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamResponse.SerializeToString,
            ),
            'GetMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeta,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.SerializeToString,
            ),
            'SubscribeMeta': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeMeta,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetResponse.SerializeToString,
            ),
            'SetSome': grpc.unary_stream_rpc_method_handler(
                    servicer.SetSome,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetSomeRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetSomeResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteResponse.SerializeToString,
            ),
            'DeleteSome': grpc.unary_stream_rpc_method_handler(
                    servicer.DeleteSome,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteSomeRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteSomeResponse.SerializeToString,
            ),
            'DeleteAll': grpc.unary_stream_rpc_method_handler(
                    servicer.DeleteAll,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteAllRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteAllResponse.SerializeToString,
            ),
            'GetAllBatched': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllBatched,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamResponse.SerializeToString,
            ),
            'SubscribeBatched': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeBatched,
                    request_deserializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamRequest.FromString,
                    response_serializer=cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudvision.arista.identityprovider.v1.SAMLConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SAMLConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetOne',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetSome',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSomeRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSomeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetAll',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/Subscribe',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetMeta',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/SubscribeMeta',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.MetaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/Set',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/SetSome',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetSomeRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigSetSomeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/Delete',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/DeleteSome',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteSomeRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteSomeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/DeleteAll',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteAllRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigDeleteAllResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllBatched(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/GetAllBatched',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeBatched(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cloudvision.arista.identityprovider.v1.SAMLConfigService/SubscribeBatched',
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamRequest.SerializeToString,
            cloudvision_dot_arista_dot_identityprovider_dot_v1_dot_services_dot_gen__pb2.SAMLConfigBatchedStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
