# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arista/arista_portal.v1/arista_portal.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'arista/arista_portal.v1/arista_portal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from fmp import extensions_pb2 as fmp_dot_extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+arista/arista_portal.v1/arista_portal.proto\x12\x17\x61rista.arista_portal.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14\x66mp/extensions.proto\"E\n\x0e\x41PITokenConfig\x12+\n\x05token\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue:\x06\xa2\x8e\x19\x02rw\"?\n\x08\x41PIToken\x12+\n\x05token\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue:\x06\xa2\x8e\x19\x02ro\"C\n\x0e\x41PIProxyConfig\x12)\n\x03url\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue:\x06\xa2\x8e\x19\x02rw\"=\n\x08\x41PIProxy\x12)\n\x03url\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue:\x06\xa2\x8e\x19\x02roB\x81\x01\n\x1b\x63om.arista.arista_portal.v1B\x0c\x41ristaPortalP\x01ZRgithub.com/aristanetworks/cloudvision-go/api/arista/arista_portal.v1;arista_portalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arista.arista_portal.v1.arista_portal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.arista.arista_portal.v1B\014AristaPortalP\001ZRgithub.com/aristanetworks/cloudvision-go/api/arista/arista_portal.v1;arista_portal'
  _globals['_APITOKENCONFIG']._loaded_options = None
  _globals['_APITOKENCONFIG']._serialized_options = b'\242\216\031\002rw'
  _globals['_APITOKEN']._loaded_options = None
  _globals['_APITOKEN']._serialized_options = b'\242\216\031\002ro'
  _globals['_APIPROXYCONFIG']._loaded_options = None
  _globals['_APIPROXYCONFIG']._serialized_options = b'\242\216\031\002rw'
  _globals['_APIPROXY']._loaded_options = None
  _globals['_APIPROXY']._serialized_options = b'\242\216\031\002ro'
  _globals['_APITOKENCONFIG']._serialized_start=126
  _globals['_APITOKENCONFIG']._serialized_end=195
  _globals['_APITOKEN']._serialized_start=197
  _globals['_APITOKEN']._serialized_end=260
  _globals['_APIPROXYCONFIG']._serialized_start=262
  _globals['_APIPROXYCONFIG']._serialized_end=329
  _globals['_APIPROXY']._serialized_start=331
  _globals['_APIPROXY']._serialized_end=392
# @@protoc_insertion_point(module_scope)
