# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arista.studio.v1.services import gen_pb2 as arista_dot_studio_dot_v1_dot_services_dot_gen__pb2


class AssignedTagsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/arista.studio.v1.AssignedTagsService/GetOne',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsResponse.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/arista.studio.v1.AssignedTagsService/GetAll',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/arista.studio.v1.AssignedTagsService/Subscribe',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamResponse.FromString,
                )


class AssignedTagsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssignedTagsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arista.studio.v1.AssignedTagsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AssignedTagsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.AssignedTagsService/GetOne',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.AssignedTagsService/GetAll',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.AssignedTagsService/Subscribe',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AssignedTagsConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/arista.studio.v1.AssignedTagsConfigService/GetOne',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigResponse.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/arista.studio.v1.AssignedTagsConfigService/GetAll',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/arista.studio.v1.AssignedTagsConfigService/Subscribe',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamResponse.FromString,
                )
        self.Set = channel.unary_unary(
                '/arista.studio.v1.AssignedTagsConfigService/Set',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigSetRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigSetResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/arista.studio.v1.AssignedTagsConfigService/Delete',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigDeleteRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigDeleteResponse.FromString,
                )


class AssignedTagsConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssignedTagsConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigSetRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigSetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigDeleteRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arista.studio.v1.AssignedTagsConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AssignedTagsConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.AssignedTagsConfigService/GetOne',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.AssignedTagsConfigService/GetAll',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.AssignedTagsConfigService/Subscribe',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.AssignedTagsConfigService/Set',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigSetRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.AssignedTagsConfigService/Delete',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigDeleteRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.AssignedTagsConfigDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class InputsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/arista.studio.v1.InputsService/GetOne',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsResponse.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/arista.studio.v1.InputsService/GetAll',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/arista.studio.v1.InputsService/Subscribe',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamResponse.FromString,
                )


class InputsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InputsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arista.studio.v1.InputsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InputsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.InputsService/GetOne',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.InputsService/GetAll',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.InputsService/Subscribe',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class InputsConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/arista.studio.v1.InputsConfigService/GetOne',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigResponse.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/arista.studio.v1.InputsConfigService/GetAll',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/arista.studio.v1.InputsConfigService/Subscribe',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamResponse.FromString,
                )
        self.Set = channel.unary_unary(
                '/arista.studio.v1.InputsConfigService/Set',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigSetRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigSetResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/arista.studio.v1.InputsConfigService/Delete',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigDeleteRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigDeleteResponse.FromString,
                )


class InputsConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InputsConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigSetRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigSetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigDeleteRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arista.studio.v1.InputsConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InputsConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.InputsConfigService/GetOne',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.InputsConfigService/GetAll',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.InputsConfigService/Subscribe',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.InputsConfigService/Set',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigSetRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.InputsConfigService/Delete',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigDeleteRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.InputsConfigDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class StudioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/arista.studio.v1.StudioService/GetOne',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioResponse.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/arista.studio.v1.StudioService/GetAll',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/arista.studio.v1.StudioService/Subscribe',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamResponse.FromString,
                )


class StudioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arista.studio.v1.StudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StudioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.StudioService/GetOne',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.StudioService/GetAll',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.StudioService/Subscribe',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class StudioConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/arista.studio.v1.StudioConfigService/GetOne',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigResponse.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/arista.studio.v1.StudioConfigService/GetAll',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/arista.studio.v1.StudioConfigService/Subscribe',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamResponse.FromString,
                )
        self.Set = channel.unary_unary(
                '/arista.studio.v1.StudioConfigService/Set',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigSetRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigSetResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/arista.studio.v1.StudioConfigService/Delete',
                request_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigDeleteRequest.SerializeToString,
                response_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigDeleteResponse.FromString,
                )


class StudioConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudioConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigSetRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigSetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigDeleteRequest.FromString,
                    response_serializer=arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arista.studio.v1.StudioConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StudioConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.StudioConfigService/GetOne',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.StudioConfigService/GetAll',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/arista.studio.v1.StudioConfigService/Subscribe',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.StudioConfigService/Set',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigSetRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arista.studio.v1.StudioConfigService/Delete',
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigDeleteRequest.SerializeToString,
            arista_dot_studio_dot_v1_dot_services_dot_gen__pb2.StudioConfigDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
