name: Run checks on PR
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  Linter:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
    - uses: actions/checkout@v4
    - name: Prepare python environment
      run: |
        pip install --no-cache-dir "cython<3.0.0"
        pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt
        pip install .
    - name: Run linter
      run: flake8 .

  Test-Runner:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
    - uses: actions/checkout@v4
    - name: Prepare python environment
      run: |
        pip install --no-cache-dir "cython<3.0.0"
        pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt
        pip install .
    - name: Run Tests
      run: pytest

  Copyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run copyright checker
      run: ./check_copyright.sh